src/components/ClaimAddress/claim-address.styles.js, src/components/ClaimAddress/index.jsx, src/components/shared/Button/Button.style.js, src/components/shared/Button/index.jsx, src/components/shared/Footer/footer.styles.js, src/components/shared/Footer/index.jsx
create button shared component
=> REV-012: create button shared component

src/components/shared/Menu/index.jsx, src/components/shared/Menu/menu.styles.js, src/components/shared/Menu/util.js, src/components/shared/Navbar/navbar.styles.js, src/utils/debounce.js, src/utils/window.js
- created a responsive dropdown shared component.
=> REV-023: created shared dropdown menu

src/components/shared/Sidebar/index.jsx, src/components/shared/Sidebar/sidebar.styles.js, src/components/verify-phone/VerifyPhoneWrapper/index.jsx, src/components/verify-phone/VerifyPhoneWrapper/verify-phone-wrapper.styles.js, src/pages/VerifyPhone.jsx, src/routes.js
=> REV-029-refactor-verify-phone-page-file-structure

public/index.html, src/components/my-roles/RoleCard/index.jsx, src/components/my-roles/RoleCard/role-card.styles.js, src/components/my-roles/RoleCardsContainer/index.jsx, src/components/my-roles/Roles/index.jsx, src/components/my-roles/Roles/roles.styles.js, src/components/my-roles/RolesTable/index.jsx, src/components/my-roles/RolesTable/roles-table.style.js
=> My-Roles Page Clean up

src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/components/listing-page/ContactForm/contact-form.styles.js, src/components/listing-page/ContactForm/index.jsx, src/components/listing-page/Details/details.styles.js, src/components/listing-page/Details/index.jsx, src/components/listing-page/Features/features.styles.js, src/components/listing-page/Features/index.jsx, src/components/listing-page/Location/index.jsx, src/components/listing-page/Location/location.styles.js, src/components/listing-page/Offer/index.jsx, src/components/listing-page/Offer/offer.styles.js, src/components/listing-page/Overview/index.jsx, src/components/listing-page/Overview/overview.styles.js, src/components/listing-page/ScheduleVisit/data.js, src/components/listing-page/ScheduleVisit/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/components/listing-page/SimilarListings/index.jsx, src/components/listing-page/SimilarListings/similar-listings.styles.js, src/components/listing-page/Slider/index.jsx, src/components/listing-page/Slider/slider.styles.js, src/components/listing-page/data.js, src/components/shared/Button/Button.style.js, src/pages/Listings/ListingPage.jsx, src/routes.js
Refactor Listing Page
- Fixed shared button cursor on hover
- Remove unneeded styles 
- Refactored some styles
=> Refactor listing page

.github/workflows/cicd.yml, .gitignore, package-lock.json
```
err: error: Your local changes to the following files would be overwritten by merge:
err: 	package-lock.json
```
In order to fix the error above, new npm package-lock was created. 🤞
=> Rebuild Package.json due to conflict 

.github/workflows/cicd.yml
Update the github action to handle local changes on the file "package-lock.json"
<Brief description of the code changes.>
=> Update GitHub action to handle local changes

src/components/my-roles/RoleCard/index.jsx, src/components/my-roles/RoleCardsContainer/data.js, src/components/my-roles/RoleCardsContainer/index.jsx, src/components/my-roles/Roles/index.jsx, src/components/shared/Sidebar/index.jsx, src/services/roles.js, src/services/user.js
- link user roles with backend
- backend PR: 
https://github.com/abukhadraop-or/reverifi-api/pull/14
=> REV-38-link user roles with backend

.github/PULL_REQUEST_TEMPLATE.md
Modify github Template to add Jira tickets as links
=> Add Jira Template

src/components/create-listing/CreateListingForm/index.jsx, src/components/create-listing/FormInputFields/index.jsx, src/pages/Listing/ListingPage.jsx, src/routes.js
- Clean up and fix `/listing` bug, page not showing.
- Fix setValues function prop in `/listing/create` form
Ref fix to [PR-47](https://github.com/abukhadraop-or/reverifi/pull/47)
=> Clean-up: Listing page create form

src/components/create-listing/CreateListingForm/index.jsx, src/components/home/FeaturedListing/index.jsx
NA
Fix updateListingForm wrong importation
Go to `/listing/create` 
Page should render without warnings/errors.
=> Hot-fix: Create listing Form field set

src/components/home/ExploreListing/explore-listing.styles.js
NA
Issue building [stage env](https://reverifi.sociumtech.com/) due to prettier [linting error](https://github.com/abukhadraop-or/reverifi/runs/5039035221?check_suite_focus=true#step:3:144).
NA
NA
=> Hot-fix: Css Stylings are failing due to prettier error

src/components/verify-phone/VerifyPhoneForm/index.jsx, src/components/verify-phone/VerifyPhoneForm/verify-phone-form.styles.js, src/components/verify-phone/VerifyPhoneWrapper/verify-phone-wrapper.styles.js
https://optimumpartners.atlassian.net/jira/software/projects/REV/boards/46?selectedIssue=REV-58
UI enhancements on phone verification, 
- figma link: https://www.figma.com/file/IKofGteYvhvMoXoafbBpgi/reverifi---Hover?node-id=0%3A2177
=> REV-58 ui-tweaks-phone-verification

src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/components/listing-page/Details/index.jsx, src/components/listing-page/Features/data.js, src/components/listing-page/Features/features.styles.js, src/components/listing-page/Features/index.jsx, src/components/listing-page/Offer/index.jsx, src/components/listing-page/Offer/offer.styles.js, src/components/listing-page/Overview/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/components/listing-page/Slider/index.jsx, src/components/shared/Navbar/navbar.styles.js, src/pages/Listing/ListingPage.jsx, src/routes.js, src/services/listing.js
https://optimumpartners.atlassian.net/browse/REV-54
connect listing page with backend
https://github.com/abukhadraop-or/reverifi-api/pull/17
open listing page with listing/id route
=> REV-54-connect listing page with backend

src/pages/Login/Login.jsx
https://optimumpartners.atlassian.net/browse/REV-64
- fix Login button font size should be 16px
=> REV-64-login-page-login-button-font-size

src/components/home/ClaimAddress/claim-address.styles.js
https://optimumpartners.atlassian.net/browse/REV-66
fix the join us banner
none
-check if home page join us banner is fixed
=> REV-66-homepage-join-us-banner-is-broken

src/components/home/Events/data.js, src/components/home/Events/index.jsx
https://optimumpartners.atlassian.net/browse/REV-65
home page upcoming slider shows two slides 
none
-check the home page events slider
=> Rev 65 homepage upcoming tab slides are broken

src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/components/home/FeaturedListingCard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-70
Homepage: featured listing cards are broken
none
-check home page listing cards working
=> REV-70-homepage featured listing cards are broken

src/components/home/Storyboard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-73
homepage search box placeholder needs to be changed
none
-check search box placeholder if the text is right
=> REV-73 homepage search box placeholder needs to be changed

src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js
https://optimumpartners.atlassian.net/browse/REV-76
-update the menu items font weight to be 600
-removed icons before the menu items
none
-check if the menu items font weight is 600
-heck if the icons before the menu items is removed
=> Rev-76 update the header menu

src/components/shared/Footer/footer.styles.js, src/components/shared/Footer/index.jsx
https://optimumpartners.atlassian.net/browse/REV-78
-change the “Subscribe to our Newsletter “ placeholder size should be “12px” and font family should be“Montserrat”
-the Email element in reverifi list in the footer should be underlined when hovering 
none
-the “Subscribe to our Newsletter “ placeholder size should be “12px” and font family should be“Montserrat”
-the Email element in reverifi list in the footer should be underlined when hovering
=> REV-78 homepage footer ui tweaks

src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js
https://optimumpartners.atlassian.net/browse/REV-77
- redirect from navbar to agent list page when click on ( find an agent)
=> REV-77-find-an-agent-should-redirect-to-agent-list

src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-69
- show validation message when user entered already registered email
=> REV-69-signup-page-no-validation-message-appears-when-entering-pre-registered-account

src/pages/Login/Login.jsx, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-74
- fix auto fill fields prevent successful login or signup
=> REV-74-login-page-and-signup-pages-auto-saved-fields-restricts-login-and-signup-procces

src/components/verify-phone/VerifyPhoneWrapper/index.jsx, src/contexts/UserContext/index.jsx, src/pages/SignUp/SignUp.jsx, src/services/auth.js
https://optimumpartners.atlassian.net/browse/REV-75
- add this text above verify phone code inputs : (Please enter the verification code we sent to your mobile **64)
- update signup functions to save phone number
=> REV-75-mobile-verification-add-a-text-above-the-code

src/components/shared/Footer/index.jsx
https://optimumpartners.atlassian.net/browse/REV-78
-"Newsletter" first letter is capitalized in placeholder
none
-"Newsletter" first letter shouldn't be capitalized in placeholder in footer
=> REV-78-homepage-footer-ui-tweaks-update

src/components/shared/FormInput/index.jsx, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-63
- fix Phone number fields should be form field that accepts numbers
- fix Placeholder for extension field should be capitalized (Ext) 
- fix Placeholder for number field should be (201) 555-0123
=> REV-63-signup-page-phone-number-fields-format-are-wrong

src/components/home/Card/card.styles.js, src/components/home/ClaimAddress/claim-address.styles.js, src/components/home/ExploreListing/explore-listing.styles.js
https://optimumpartners.atlassian.net/browse/REV-67
-  remove the hover from attendees icon
- add Margin-bottom to become 32px to explore our listings  
- Align claim your address with the from field
=> REV-67-homepage-enhancements

src/pages/SignUp/sign-up-schema.js
https://optimumpartners.atlassian.net/browse/REV-71
- add restrictions Password field
=> REV-71-signup-page-no-restrictions-on-password-field

src/pages/Login/Login.jsx, src/pages/Login/login.styles.js
https://optimumpartners.atlassian.net/browse/REV-68
- show error message if the password or email is wrong
=> REV-68-login-page-email-and-password-fields-validation-messages-are-not-appeared

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js, src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js, src/components/shared/Navbar/index.jsx, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-79
https://optimumpartners.atlassian.net/browse/REV-84
https://optimumpartners.atlassian.net/browse/REV-85
- add route to my profile page from navbar
- fix phone number and zip code fields
- fix name and description is empty when no data fetched from server
=> REV-79-account-settings-should-redirect-to-my-profile-page

src/components/agent-list/AgentCard/agent-card.styles.js, src/components/agent-list/AgentCard/index.jsx, src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-80
-First letter of agent's name should be capitalized
-Fixed The line below the address is doubled in the first, second and last row of cards
-Added for First three digits of phone number should be wrapped in parentheses and a dash is required between the sixth and the seventh numbers
-Fixed mouse hover should be changed to a pointer (hand cursor) whenever hovering on the phone symbol at the bottom of the card
-Fixed email text colour should be a bit lighter
-The contact button should have a lesser height and more width
-Removed black boxes that are shown when clicking on search for location and agent's name
=> REV-80 agents list page enhacments

src/components/shared/Navbar/navbar.styles.js
https://optimumpartners.atlassian.net/browse/REV-81
- fix navbar search placholder 
- user info spacing
=> REV-81-header-search-for-property-placeholder-sapces-between-profile-image-and-name

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
https://optimumpartners.atlassian.net/browse/REV-88
- change select menu colors
=> REV-88-my-profile-x-button-hover-state-selected-items-design

src/components/shared/Navbar/index.jsx
https://optimumpartners.atlassian.net/browse/REV-95
- valdations already fixed on other tickets.
- fix redirects of the navbar (join now, signin, signut)
=> REV-95-my-profile-save-personal-information-validation-messages

src/components/verify-phone/VerifyPhoneWrapper/index.jsx, src/pages/SignUp/SignUp.jsx, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-91
-  redirect to verify phone page when signup if the user enter his phone
=> REV-91-clicking-on-continue-should-redirect-to-phone-verification-page

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js, src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
https://optimumpartners.atlassian.net/browse/REV-83
- fix validation 
- add data saved message
=> REV-83-my-profile-fields-capitalization-issues

src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/components/home/FeaturedListingCard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-82
-Fixed listing cards
=> Rev-82 homepage featured listing card fix

src/components/my-roles/RoleCardsContainer/data.js, src/components/my-roles/RolesTable/roles-table.style.js
https://optimumpartners.atlassian.net/browse/REV-96
-Icons do not match their corresponding roles
-A circle should wrap the pen icon in the bottom box when hovering on it instead of a square
=> REV-96 my role page issues

src/components/agent-list/AgentCard/index.jsx, src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
https://optimumpartners.atlassian.net/browse/REV-80
-There should  vertical separation lines between the three search search categories in the search field .
-The first letter of the company below the name of  should be capitalized.
=> REV-80 agents list page borders

src/pages/Login/Login.jsx
https://optimumpartners.atlassian.net/jira/software/projects/REV/boards/46?selectedIssue=REV-68
- fix password and email validation message text and position
=> REV-68-login-page-email-and-password-fields-validation-messages-are-not-appeared-FIX

src/components/my-profile/MyProfileWrapper/index.jsx
https://optimumpartners.atlassian.net/jira/software/projects/REV/boards/46?selectedIssue=REV-95
- fix auto save issue
=> REV-95-my-profile-save-personal-information-validation-messages-FIX

src/pages/Login/Login.jsx, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/jira/software/projects/REV/boards/46?selectedIssue=REV-74
- fix auto save issue of the email and passsword
=> REV-74-login-page-and-signup-pages-auto-saved-fields-restricts-login-and-signup-procces-FIX

src/components/my-profile/MyProfileWrapper/index.jsx, src/contexts/UserContext/index.jsx
https://optimumpartners.atlassian.net/browse/REV-100
- update navbar info when user updated them from my profile page
=> REV-100-name-does-not-get-reflected-directly-after-editing

src/utils/helpers.js
- fix phone format function to accept any number length
=> fix phone format function

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/shared/Toast/toast.styles.js, src/hooks/use-show-toast-bar.js, src/hooks/use-timer.js
https://optimumpartners.atlassian.net/browse/REV-93
- add timer to hide toast message
=> REV-93-my-profile-add-save-changes-toast-message-FIX

src/components/home/ClaimAddress/index.jsx
https://optimumpartners.atlassian.net/browse/REV-99
- Join us button in join us banner should redirect to the registration page
=> REV-99-join-us-button-should-redirect-to-signup-page

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/shared/Toast/toast.styles.js, src/contexts/UserContext/index.jsx
https://optimumpartners.atlassian.net/browse/REV-100
- fix username not updated on the header when user change it on my profile and update the toast message
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/25
=> REV-100-name-does-not-get-reflected-directly-after-editing-FIX

src/components/agent-list/AgentCard/agent-card.styles.js, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js, src/pages/SignUp/SignUp.jsx, src/pages/SignUp/sign-up-schema.js, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-115
- fix name input fields in signup page and my profile page
- fix username style if it's too long
- create 2 function to handle numbers and text fields
=> REV-115-design-get-ruined-when-the-name-is-long

src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js, src/components/agent-list/AgentCardsContainer/index.jsx, src/components/agent-list/DesktopFilterSection/index.jsx, src/services/user.js
https://optimumpartners.atlassian.net/browse/REV-111
- Improve agent list search
- backend PR:  https://github.com/abukhadraop-or/reverifi-api/pull/26
=> REV-111-find-an-agent-filtration-and-search-issues

src/components/shared/FormInput/form-input.styles.js, src/pages/SignUp/SignUp.jsx, src/pages/SignUp/sign-up-schema.js, src/pages/SignUp/sign-up.styles.js
https://optimumpartners.atlassian.net/browse/REV-116
phone number and password inputs validation
=> REV-116-sign up validation messages and other issues

src/components/dashboard/DashboardWrapper/index.jsx, src/components/how-we-work/HowWeWorkWrapper/how-we-work.styles.js, src/components/how-we-work/HowWeWorkWrapper/index.jsx, src/components/how-we-work/ListingsTable/data.js, src/components/how-we-work/ListingsTable/index.jsx, src/components/how-we-work/ListingsTable/listings-table.styles.js, src/components/how-we-work/data.js, src/components/my-roles/Roles/index.jsx, src/components/shared/Table/index.jsx, src/components/shared/Table/table-styles.js, src/pages/HowWeWork.jsx, src/routes.js
https://optimumpartners.atlassian.net/browse/REV-130
- create how we work page
- figma link: https://www.figma.com/file/IKofGteYvhvMoXoafbBpgi/reverifi---Hover?node-id=327%3A6647
=> REV-130-create-how-we-work

src/assets/add-icon-small.svg, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js, src/components/shared/FormInput/form-input.styles.js, src/components/shared/FormInput/index.jsx, src/components/shared/Sidebar/index.jsx, src/contexts/UserContext/index.jsx, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-112
- Selected and not selected items in languages and service areas fields should have the same space from the left border of the drop down list. 
- Plus symbol should get entered in the phone field even if there are no already entered numbers
- Settings icon's design should match the design in figma
- Information should be saved when selecting them from autofill data
- Company information data should not disappear after refreshing
- Company and website in company information should not accept only numbers or only special characters
- Backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/27
=> REV-112-profile-page-design-and-functionalities-issues

src/components/my-listings/ListingsTable/index.jsx, src/services/listing.js
fixed my listings
https://github.com/abukhadraop-or/reverifi-api/pull/29
=> my listing fix

src/components/my-listings/ListingsTable/index.jsx
fixed my listing page image error
=> fixed my listings bug

src/components/my-listings/ListingsTable/index.jsx, src/contexts/UserContext/index.jsx, src/services/listing.js
https://optimumpartners.atlassian.net/browse/REV-124
- modify user context and user listings service
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/28
=> REV-124-FIX

src/components/agent-details/AgentInformation/index.jsx, src/components/agent-details/CardImage/index.jsx, src/components/agent-details/CardInformation/index.jsx, src/components/my-profile/MyProfileWrapper/index.jsx, src/utils/helpers.js
=> fix agent details page

src/components/how-we-work/ListingsTable/index.jsx, src/components/how-we-work/ListingsTable/listings-table.styles.js
https://optimumpartners.atlassian.net/browse/REV-130
- fix how we work page table alignment
=> REV-130-FIX

src/components/my-listings/ListingsTable/index.jsx, src/components/shared/Sidebar/sidebar.styles.js, src/services/listing.js
=> fix for backend

src/components/home/ClaimAddress/index.jsx
https://optimumpartners.atlassian.net/browse/REV-137
hide join us banner for logged in users
=> REV-137 hide join us bannerfor logged in users

src/components/agent-list/AgentCard/agent-card.styles.js, src/components/agent-list/AgentCard/index.jsx, src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js, src/components/agent-list/AgentCardsContainer/index.jsx, src/components/home/FeaturedListing/index.jsx, src/components/shared/Tooltip/index.jsx, src/components/shared/Tooltip/tooltip.styles.js
https://optimumpartners.atlassian.net/browse/REV-143
fixed agent list bugs
=> fixed agent list

src/components/shared/Sidebar/index.jsx, src/components/shared/Sidebar/sidebar.styles.js
=> menu arrow fix

src/components/listing-search-page/Card/card.style.js, src/components/listing-search-page/Card/index.jsx, src/components/listing-search-page/ListingSearch/index.jsx, src/components/listing-search-page/ListingSearch/listing-search.style.js, src/components/listing-search-page/NearbyListings/index.jsx, src/components/listing-search-page/NearbyListings/nearby-listings.style.js, src/components/listing-search-page/SearchHeader/index.jsx, src/components/listing-search-page/SearchHeader/search-header.style.js, src/components/listing-search-page/SearchList/index.jsx, src/components/listing-search-page/SearchList/search-list.style.js, src/components/listing-search-page/SearchResults/index.jsx, src/components/shared/Map/map.styles.js
https://optimumpartners.atlassian.net/browse/REV-154
search listing updates
=> REV-154-search listing updates

src/pages/SignUp/sign-up-schema.js, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-126
- fix phone number bugs in signup and my profile
=> REV-126-sign-up-my-profile-extension-and-phone-number-fields-accept-alphabets-and-special-characters

src/components/my-profile/MyProfileWrapper/index.jsx
- fix  unique company email issue
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/32
=> fix company details update issue

src/components/agent-list/AgentCard/agent-card.styles.js, src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
https://optimumpartners.atlassian.net/browse/REV-117
- fix UI bugs
=> REV-117-fix

src/components/agent-details/ContactAgent/contact-agent.style.js, src/components/agent-details/ContactAgent/index.jsx, src/components/create-listing/CreateListingForm/index.jsx, src/components/create-listing/FormInputFields/index.jsx, src/components/home/FeaturedListingCard/index.jsx, src/components/listing-page/ContactForm/contact-form-schema.js, src/components/listing-page/ContactForm/contact-form.styles.js, src/components/listing-page/ContactForm/index.jsx, src/components/listing-page/Details/details.styles.js, src/components/listing-page/Details/index.jsx, src/components/listing-page/Offer/index.jsx, src/components/listing-page/Offer/offer.styles.js, src/components/listing-page/Overview/index.jsx, src/components/listing-page/Overview/overview.styles.js, src/components/listing-page/ScheduleVisit/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-148
listing details bug fixing
=> REV-148 listing details page bugs

src/components/agent-details/CardInformation/index.jsx, src/components/home/FeaturedListingCard/index.jsx, src/components/listing-page/Details/index.jsx
- fix apartment and garage texts to match the backend
- Backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/33
=> REV-158-remove-s-from-apartments-and-add-s-to-garage-back-end

src/components/listing-search-page/Card/card.style.js, src/components/listing-search-page/Card/index.jsx, src/components/listing-search-page/ListingSearch/listing-search.style.js, src/components/listing-search-page/NearbyListings/nearby-listings.style.js, src/components/listing-search-page/SearchHeader/index.jsx, src/components/listing-search-page/SearchHeader/search-header.style.js, src/components/listing-search-page/SearchList/index.jsx, src/components/listing-search-page/SearchList/search-list.style.js, src/components/shared/DropdownMenu/dropdown-menu.styles.js
https://optimumpartners.atlassian.net/browse/REV-159
search listings page
=> REV-159 search listings page

src/components/shared/AdminPanelLayout/admin-panel-layout.styles.js, src/components/shared/Sidebar/sidebar.styles.js
https://optimumpartners.atlassian.net/browse/REV-151
- fix sidebar styles
=> REV-151-fix-lhs-menubar

src/components/agent-details/AgentInformation/agent-information.style.js, src/components/agent-details/AgentInformation/index.jsx, src/components/agent-details/AgentListings/agent-listings.style.js, src/components/agent-details/AgentRating/agent-rating.style.js, src/components/agent-details/AgentRating/index.jsx, src/components/agent-details/CardInformation/card-information.style.js, src/components/agent-details/CardInformation/index.jsx, src/components/agent-details/ContactAgent/contact-agent.style.js, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js, src/components/shared/FormTextArea/index.jsx, src/components/shared/LikeButton/like-button.styles.js, src/pages/SignUp/sign-up-schema.js
https://optimumpartners.atlassian.net/browse/REV-145
https://optimumpartners.atlassian.net/browse/REV-147
- agent profile page fixes
=> agent profile page fixes

src/components/create-listing/FormInputFields/index.jsx, src/components/listing-page/Offer/index.jsx, src/components/listing-page/Offer/offer.styles.js, src/components/listing-page/Overview/overview.styles.js, src/components/shared/FormInput/form-input.styles.js
https://optimumpartners.atlassian.net/browse/REV-148
fixed listing details page bugs
=> REV-148 listing fix

src/components/create-listing/FormInputFields/index.jsx, src/components/shared/FormSelectInput/index.jsx, src/components/shared/FormSelectInput/select.styles.js
https://optimumpartners.atlassian.net/browse/REV-155
create new listing enhancemnts
=> REV-155-create new listing enhancemnts

src/components/agent-details/ContactAgent/index.jsx, src/components/listing-page/ContactForm/contact-form.styles.js, src/components/listing-page/ContactForm/index.jsx, src/components/listing-page/Details/details.styles.js, src/components/listing-page/Offer/offer.styles.js, src/components/listing-page/Overview/index.jsx, src/components/listing-page/Overview/overview.styles.js, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/components/listing-page/data.js
https://optimumpartners.atlassian.net/browse/REV-149
listing details page enhancement
=> REV-149 listing details page enhancements

src/components/agent-details/AgentInformation/agent-information.style.js, src/components/agent-details/AgentRating/agent-rating.style.js, src/components/agent-details/CardInformation/card-information.style.js, src/components/agent-details/CardInformation/index.jsx, src/components/agent-details/ContactAgent/contact-agent.style.js, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js, src/components/shared/FormInput/form-input.styles.js, src/components/shared/FormTextArea/form-text-area.styles.js, src/components/shared/FormTextArea/index.jsx
https://optimumpartners.atlassian.net/browse/REV-145
https://optimumpartners.atlassian.net/browse/REV-147
https://optimumpartners.atlassian.net/browse/REV-112
- Agent profile and my profile bugs fixes
=> Agent profile and my profile bugs fixes

src/components/home/FeaturedListingCard/index.jsx, src/components/shared/SaveAndShareButtons/index.jsx
https://optimumpartners.atlassian.net/browse/REV-176
- fix save button not activated on homepage
=> REV-176-save-status-is-not-reflected-on-save-icon-on-overlay-or-without-it

src/components/agent-list/AgentCard/index.jsx, src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js, src/components/home/FeaturedListing/index.jsx, src/components/shared/Tooltip/index.jsx, src/components/shared/Tooltip/tooltip.styles.js
https://optimumpartners.atlassian.net/browse/REV-161
- fix bugs
=> REV-161-remove-fields-borders

src/components/create-listing/CreateListingForm/index.jsx, src/components/create-listing/FormInputFields/index.jsx
https://optimumpartners.atlassian.net/browse/REV-153
- fix bugs
=> REV-153- fix

src/components/saved-agents-listings/SavedAgentsListingsWrapper/index.jsx
- fix saved agents listings tabs not shown
=> fix-saved-agents-listings

src/components/edit-listing/Tabs/index.jsx
https://optimumpartners.atlassian.net/browse/REV-181
- fix tabs not shown in edit listing page
=> REV-181-details-schedule-reverifi-tabs-are-not-shown-in-edit-listing-page

src/components/shared/Navbar/index.jsx
https://optimumpartners.atlassian.net/browse/REV-187
- fix bug
=> REV-187-page-title-should-be-saved-not-saved-listings-in-header-menu

src/components/agent-details/AgentListings/index.jsx, src/components/agent-details/CardImage/card-image.style.js, src/components/agent-details/CardImage/index.jsx, src/components/create-listing/FormInputFields/form-input-fields.styles.js, src/components/create-listing/FormInputFields/index.jsx
https://optimumpartners.atlassian.net/browse/REV-180
- add special tags enhancements
=> REV-180-tags-selection-enhancement   

src/components/shared/Table/table-styles.js
https://optimumpartners.atlassian.net/browse/REV-193
- fix bugs
=> REV-193-saved-page-top-edges-of-tables-should-be-rounded

src/components/edit-listing-schedule/ListingSchedule/index.jsx, src/components/listing-page/Overview/index.jsx, src/components/listing-page/ScheduleVisit/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/components/my-listings/ListingsTable/listing-table.style.js, src/components/saved-agents-listings/SavedAgents/index.jsx, src/components/saved-agents-listings/SavedListings/index.jsx, src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
https://optimumpartners.atlassian.net/browse/REV-199
fix saved page arrows at the bottom bugs
=> REV-199 saved page arrows at the bottom behaviour

src/components/saved-agents-listings/SavedAgents/index.jsx
https://optimumpartners.atlassian.net/browse/REV-189
- fix bugs
=> REV-189-saved-listing-saved-agent-pages

src/components/saved-agents-listings/SavedAgents/index.jsx, src/components/shared/Table/table-styles.js
https://optimumpartners.atlassian.net/browse/REV-195
- fix bugs
=> REV-195-my-roles-column-saved-agents-tab

src/components/saved-agents-listings/SavedAgents/index.jsx
https://optimumpartners.atlassian.net/browse/REV-196
- fix bugs
=> REV-196-the-saved-agents-page-design-is-ruined-when-agents-have-long-name-phone-roles-email-address-infromation

src/components/listing-search-page/Card/card.style.js
https://optimumpartners.atlassian.net/browse/REV-190
- fix search listings card image size
=> REV-190-search-listings-page-labels-are-wrapped-and-truncated

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/saved-agents-listings/SavedListings/index.jsx
https://optimumpartners.atlassian.net/browse/REV-198
- fix saved listings and agent not shown when profile is updated
=> REV-198-saved-saved-listings-saved-agents-disappear-when-editing-my-profile-informtion

src/components/saved-agents-listings/SavedAgents/index.jsx
https://optimumpartners.atlassian.net/browse/REV-200
- fix non agents users shown in the saved agents
=> REV-200-saved-the-user-is-still-in-saved-agents-page-even-when-they-are-not-agents-anymore

src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-201
- add limit to max length of signup email
=> REV-201-saved-signing-up-using-long-email-will-ruin-saved-agents-page-design

src/components/how-we-work/ListingsTable/index.jsx, src/components/listing-page/ScheduleVisit/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/components/my-listings/ListingsTable/listing-table.style.js, src/components/my-roles/RolesTable/index.jsx, src/components/my-roles/RolesTable/roles-table.style.js, src/components/shared/Tooltip/index.jsx, src/components/shared/Tooltip/tooltip.styles.js
https://optimumpartners.atlassian.net/browse/REV-204
update my roles table
=> REV-204 my roles update the table

src/components/listing-search-page/ListingSearch/index.jsx, src/components/listing-search-page/SearchHeader/index.jsx
https://optimumpartners.atlassian.net/browse/REV-258
- fix listing search input field clear
=> REV-258-search-clicking-on-x-button-should-not-reset-the-query

src/components/agent-details/AgentRating/index.jsx
https://optimumpartners.atlassian.net/browse/REV-202
- fix agent details review date
=> REV-202-rate-review-date

src/components/agent-details/AgentRating/index.jsx, src/components/shared/FormTextArea/index.jsx
https://optimumpartners.atlassian.net/browse/REV-203
- fix review limit not reset
=> REV-203-rate-review-when-editing-one-of-the-reviews-and-saving-it-the-char-number-doesnt-change

src/components/create-listing/CreateListingForm/index.jsx
https://optimumpartners.atlassian.net/browse/REV-156
edit listing page issues
=> REV-156 edit listings page issues

src/components/listing-page/ScheduleVisit/index.jsx
https://optimumpartners.atlassian.net/browse/REV-232
fix first day in schedule
=> REV-232-schedule the first scheduled visiting time isnt reflected on listing details page

src/components/listing-page/ScheduleVisit/data.js
https://optimumpartners.atlassian.net/browse/REV-236
fix schedule slider
=> REV-236 schedule listing detailed page

src/components/home/Storyboard/index.jsx, src/components/listing-search-page/Card/card.style.js, src/components/listing-search-page/Card/index.jsx, src/components/listing-search-page/MapCard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-252
https://optimumpartners.atlassian.net/browse/REV-253
https://optimumpartners.atlassian.net/browse/REV-256
- fix search listing bugs
- backebd PR: https://github.com/abukhadraop-or/reverifi-api/pull/43
=> REV-252-search-listing-data-are-not-rendering-correctly

src/components/agent-details/AgentRating/agent-rating.style.js
https://optimumpartners.atlassian.net/browse/REV-211
- fix review card
=> REV-211-rate-review-broken-ratings-reviews-and-date-time-at-certain-viewports

src/components/edit-listing-schedule/DateInput/date-input.style.js, src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.style.js, src/components/edit-listing-schedule/ListingSchedule/index.jsx, src/components/edit-listing-schedule/ListingSchedule/listing-schedule-schema.js, src/components/edit-listing-schedule/TimeInput/index.jsx, src/components/edit-listing-schedule/TimeInput/time-input.style.js, src/components/listing-page/ScheduleVisit/index.jsx, src/components/listing-page/ScheduleVisit/schedule-visit.styles.js, src/utils/helpers.js
=> REV-260 fix schedule bugs

src/components/home/Storyboard/index.jsx, src/components/shared/Map/index.jsx
=> Hot fix homepage search input

src/components/listing-search-page/SearchList/index.jsx, src/components/listing-search-page/SearchResults/listing-search-cards.style.js
https://optimumpartners.atlassian.net/browse/REV-261
- fix listings search page
=> REV-261-search-listings-page-number-of-listings-in-subtitle-doesnt-match-with-the-number-of-listings-card-shown

src/components/listing-search-page/MapCard/index.jsx, src/components/listing-search-page/MapCard/map-card.style.js
https://optimumpartners.atlassian.net/browse/REV-266
- fix map card styles
=> REV-266-search-listings-update-search-cards

src/components/shared/Table/table-styles.js
https://optimumpartners.atlassian.net/browse/REV-247
- fix table header padding
=> REV-247-saved-fix-tables-alignments

src/components/listing-search-page/ListingSearch/index.jsx, src/components/listing-search-page/SearchHeader/index.jsx, src/components/listing-search-page/SearchHeader/search-header.style.js, src/components/shared/DropdownMenu/dropdown-menu.styles.js
https://optimumpartners.atlassian.net/browse/REV-268
- add autocomplete to search listing input filed
=> REV-268-search-listing-auto-complete-is-not-provided-for-listings-search-box

src/components/create-listing/CreateListingForm/create-listing-form-schema.js, src/components/create-listing/FormInputFields/index.jsx, src/components/create-listing/ListingImageInput/index.jsx, src/components/create-listing/ListingImageInput/listingImageInput.styles.js, src/components/edit-listing-schedule/TimeInput/index.jsx, src/components/shared/FormInput/form-input.styles.js, src/components/shared/FormSelectInput/index.jsx, src/components/shared/FormSelectInput/select.styles.js, src/utils/helpers.js
https://optimumpartners.atlassian.net/browse/REV-225
fix create listing bugs
=> REV-225 create new listing update year built validation message

src/components/how-we-work/ListingsTable/index.jsx, src/components/my-listings/ListingsHeader/listings-header.style.js, src/components/my-listings/ListingsTable/index.jsx, src/components/my-listings/MyListings/index.jsx, src/components/my-listings/MyListings/my-listings.js, src/components/my-roles/RolesTable/index.jsx, src/components/saved-agents-listings/SavedAgents/index.jsx, src/components/saved-agents-listings/SavedListings/index.jsx, src/components/saved-agents-listings/SavedListings/saved-listings.styles.js, src/components/shared/Pagination/index.jsx, src/components/shared/Pagination/pagination.styles.js, src/utils/constants.js
create shared pagination component
=> create shared pagination component

src/components/agent-details/AgentInformation/index.jsx
https://optimumpartners.atlassian.net/browse/REV-218
- fix agent details page social buttons
=> REV-218-agent-profile-hide-social-media-icons-when-no-social-accounts-inserted

src/components/agent-details/AgentRating/agent-rating.style.js, src/components/agent-details/AgentRating/index.jsx, src/components/agent-details/CardImage/card-image.style.js
https://optimumpartners.atlassian.net/browse/REV-217
https://optimumpartners.atlassian.net/browse/REV-216
- add 's' to rating word, and add message when there is no reviews
=> REV-217-rate-and-review-rating-with-s

src/components/create-listing/FormInputFields/index.jsx
https://optimumpartners.atlassian.net/browse/REV-222
https://optimumpartners.atlassian.net/browse/REV-229
- fix special tags input
=> REV-222-special-tags-deleting-any-of-tags-wont-produce-the-tags-menu-again

.eslintrc, .github/workflows/cicd.yml, .gitignore
NA
Removal of `node_modules` npm ci command since `package-lock.json` is not utilized.
NA
NA
=> Hot-fix: Release update, Remove node_modules duplicate cmds

src/components/shared/Navbar/index.jsx, src/components/shared/Sidebar/index.jsx, src/components/shared/Sidebar/sidebar.styles.js
https://optimumpartners.atlassian.net/browse/REV-224
https://optimumpartners.atlassian.net/browse/REV-219
- fix sidebar logout button and cahnge 'listing propertires' to 'my listings'
=> REV-224-lhs-menu-logout-is-not-working

src/components/edit-listing-schedule/ListingSchedule/index.jsx, src/components/edit-listing-schedule/TimeInput/index.jsx, src/components/edit-listing-schedule/TimeInput/time-input.style.js, src/components/listing-page/ScheduleVisit/data.js, src/components/listing-page/ScheduleVisit/index.jsx
https://optimumpartners.atlassian.net/browse/REV-280
schedule request time tost message
=> REV-280-schedule request time toast message

src/components/create-listing/CreateListingForm/index.jsx
- fix agent, onwer buttons not updated and features not filled in edit listing page
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/46
=> REV-246-edit-listing-i-am-seller-and-seller-agent-buttons-features-updates

src/components/listing-search-page/SearchHeader/filter-data.js, src/components/shared/Table/table-styles.js, src/components/transaction-info/ListingsTable/index.jsx, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx, src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js, src/components/transaction/CloseDealWrapper/index.jsx, src/pages/Transaction/CloseDeal.jsx, src/pages/Transaction/routes.js, src/services/listing.js, src/services/transactions.js, src/utils/constants.js
https://optimumpartners.atlassian.net/browse/REV-135
add transactions step 4
=> REV-135 transaction flow-step 04

src/components/edit-listing-schedule/DateInput/date-input.style.js, src/components/edit-listing-schedule/DateInput/index.jsx, src/components/edit-listing-schedule/TimeInput/time-input.style.js, src/components/home/Storyboard/index.jsx, src/components/listing-search-page/ListingSearch/index.jsx, src/components/listing-search-page/SearchHeader/index.jsx, src/components/listing-search-page/SearchList/index.jsx, src/components/listing-search-page/SearchList/search-list.style.js, src/components/shared/CustomMenuList/index.jsx, src/utils/constants.js
https://optimumpartners.atlassian.net/browse/REV-299
add map to search page when no results
=> REV-299-search listing page

.github/workflows/cicd.yml
=> Update npm commands

src/components/shared/DropdownMenu/index.jsx, src/components/shared/FormInput/index.jsx, src/components/shared/TransactionSelectInput/index.jsx, src/components/shared/TransactionSelectInput/transaction-select-input.styles.js, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx, src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js, src/components/transaction/AddPartiesWrapper/index.jsx, src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper-schema.js, src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper.styles.js, src/components/transaction/AssignTasksWrapper/index.jsx, src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js, src/components/transaction/CloseDealWrapper/index.jsx, src/components/transaction/UploadDocumentsWrapper/index.jsx, src/pages/Transaction/AssignTasks.jsx, src/services/transactions.js
https://optimumpartners.atlassian.net/browse/REV-346
- connect transaction step 1 and step 2
- backend PR:  https://github.com/abukhadraop-or/reverifi-api/pull/55
=> REV-346-connect-step-01-step-02

Dockerfile, docker-compose.yml, src/components/create-listing/ListingImageInput/index.jsx, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/shared/UploadInput/index.jsx, src/components/shared/UploadInput/uploadInput.styles.js, src/components/transaction/UploadDocumentsWrapper/index.jsx, src/services/upload.js
REV-390-uploading-assets
Call upload/image endpoint
Population and validation of data (logic only) was handled.
TBD:
Styling for buttons for editing a profile picture.
Updating user information on the backend side with the new image url.
=> REV-390-uploading-assets- Single image upload

src/components/transaction/CloseDealWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-418
- fix change ownerId and agentId when close deal
- Backeend PR: https://github.com/abukhadraop-or/reverifi-api/pull/61
=> REV-418-transaction-for-the-recipient-when-the-deal-is-closed

src/components/home/Events/events.styles.js, src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/pages/SignUp/SignUp.jsx
https://optimumpartners.atlassian.net/browse/REV-414
- fix signup issue and add some ui enhancement to homepage
=> REV-414-signup-is-not-working

src/components/shared/Navbar/index.jsx, src/pages/SignUp/SignUp.jsx
=> fix signup

.github/workflows/cicd.yml
=> Adding Google / Facebook env vars to the CICD

src/components/achievements/achievementsSidebar/index.jsx, src/pages/SignUp/SignUp.jsx
=> Remove registration ponts

src/components/dashboard/InvitationsTable/index.jsx, src/components/shared/Table/table-styles.js, src/components/transaction-info/ListingsTable/index.jsx, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/pages/SignUp/sign-up-schema.js
https://optimumpartners.atlassian.net/browse/REV-422
fixed dashboard buttons
=> REV-422-dashboard accepted and declined buttons

src/pages/SignUp/SignUp.jsx
=> clean code

src/components/transaction-info/ListingsTable/index.jsx, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx, src/components/transaction-info/TransactionsTable/transactions-table.styles.js, src/components/transaction/AddPartiesWrapper/index.jsx, src/components/transaction/AssignTasksWrapper/index.jsx, src/components/transaction/CloseDealWrapper/index.jsx, src/components/transaction/TransactionSharedComponent/index.jsx, src/components/transaction/UploadDocumentsWrapper/index.jsx, src/pages/Transaction/routes.js, src/utils/constants.js
- add cancel transaction logic to step 4 and continue transaction logic to transaction pgae
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/63
=> REV-412-transaction-the-user-should-be-able-to-go-to-the-four-transaction-flow-steps-from-my-transactions-table

.eslintrc, src/components/achievements/achievementsSidebar/index.jsx, src/pages/SignUp/SignUp.jsx
=> remove eslint error

src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js
https://optimumpartners.atlassian.net/browse/REV-441
remove loading between pages
=> REV-441-loading issue while navigating between pages

src/components/transaction/TransactionListingDataWrapper/index.jsx, src/components/transaction/UploadDocumentsWrapper/index.jsx, src/components/transaction/UploadDocumentsWrapper/upload-documents-wrapper.styles.js, src/services/transactions.js
https://optimumpartners.atlassian.net/browse/REV-457
- fix upload document page
- bacend PR: https://github.com/abukhadraop-or/reverifi-api/pull/74
=> REV-457-transaction-uploads-are-the-same-once-uploaded-for-all-transactions

src/components/dashboard/InvitationsTable/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx
https://optimumpartners.atlassian.net/browse/REV-413
- fix transaction table and invitation table
=> REV-413-dashboard-invitation-when-the-user-sends-transaction-invitation-it-should-only-be-reflected-on-sent-tab

src/components/achievements/achievementsSidebar/achievements-sidebar.styles.js, src/pages/SignUp/SignUp.jsx
=> add points on registration

src/components/dashboard/InvitationsTable/index.jsx, src/components/dashboard/InvitationsTable/invitations-table.styles.js
https://optimumpartners.atlassian.net/browse/REV-463
- fix invitation table
=> REV-463-update-docs-title-for-nj-only

src/components/transaction/AddPartiesWrapper/index.jsx, src/components/transaction/AssignTasksWrapper/index.jsx, src/components/transaction/InviteModal/index.jsx, src/utils/constants.js
https://optimumpartners.atlassian.net/browse/REV-439
- fill inputs of the invited user
=> REV-439-input-in-invitation-pop-up-to-be-reflected-on-origin-field

src/components/dashboard/InvitationsTable/index.jsx
=> REV-435-fix invitation table

src/components/transaction-info/TransactionsTable/index.jsx
https://optimumpartners.atlassian.net/browse/REV-466
- fix transaction table filtration
=> REV-466-my-transactions-for-the-buyer-team-the-transaction-isnt-displayed-on-their-my-transactions-table

docker-compose.yml, src/components/transaction/AgentCard/agent-card.styles.js, src/components/transaction/AgentCard/index.jsx, src/components/transaction/DataCard/data-card.styles.js, src/components/transaction/DataCard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-436
fix transaction email text cutoff
=> REV-436 transaction add involved parties email

src/components/transaction/UploadDocumentsWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-460
- remove print and download icons
=> REV-460-step-03-download-is-not-working-print-to-be-removed

src/components/my-listings/ListingsTable/listing-table.style.js
https://optimumpartners.atlassian.net/browse/REV-461
=> REV-461 fix my listings table as expected design

src/components/home/FeaturedListingCard/featured-listing-card.styles.js, src/components/home/FeaturedListingCard/index.jsx
=> fix design

src/components/shared/LocationSearchInput/search-input.style.js
https://optimumpartners.atlassian.net/browse/REV-311
=> REV-311 fix overlapping for autocomplete listing

src/components/my-roles/RolesTable/index.jsx
=> REV-292 fix tool-tip issue

src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
=> REV-244 fix saved listing issue

src/components/shared/DatePickerInput/date-picker-input.styles.js, src/components/shared/DatePickerInput/index.jsx, src/components/transaction/AssignTasksWrapper/assign-processes-schema.js, src/components/transaction/AssignTasksWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-444
- finish convert range of dates to single date transition step 2
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/77
=> REV-444-step-02-dates-should-be-single-date

src/components/my-profile/MyProfileWrapper/index.jsx, src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js, src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js, src/contexts/UserContext/index.jsx
https://optimumpartners.atlassian.net/browse/REV-468
- upload user profile image
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/76
=> REV-468-profile-page-profile-image-is-not-working

src/components/agent-details/AgentRating/agent-rating.style.js, src/components/my-roles/RoleCard/role-card.styles.js, src/components/my-roles/Roles/index.jsx, src/components/my-roles/Roles/roles.styles.js
=> REV-141 fix some issues

src/components/shared/Button/Button.style.js
https://optimumpartners.atlassian.net/browse/REV-221
=> REV-221 fix button on edit listings as on figma

src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
https://optimumpartners.atlassian.net/browse/REV-362
=> REV-362 fix services and languages area select

src/components/shared/DatePickerInput/date-picker-input.styles.js, src/components/shared/TransactionSelectInput/transaction-select-input.styles.js, src/components/transaction/AssignTasksWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-444
- fix transaction step 2 styles
=> REV-444-fix

src/components/home/Storyboard/index.jsx, src/components/shared/Toast/index.jsx, src/components/shared/Toast/toast.styles.js, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js, src/components/transaction/CloseDealWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-399
add toast message
=> REV-399-step-01 add new field for final selling price

src/components/transaction-info/ListingsTable/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx
https://optimumpartners.atlassian.net/browse/REV-377
- add roles permissions to transaction table
=> REV-377-access-to-transaction-to-be-granted-to-certain-roles

src/components/dashboard/DashboardWrapper/index.jsx, src/components/dashboard/InvitationsTable/index.jsx, src/components/dashboard/OffersTable/index.jsx, src/components/listing-page/SubmitOffer/index.jsx, src/components/my-roles/RolesTable/index.jsx, src/components/shared/TableNoData/index.jsx, src/components/shared/TableNoData/table-no-data.style.js, src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction/AgentCard/agent-card.styles.js, src/components/transaction/AgentCard/index.jsx, src/components/transaction/DataCard/data-card.styles.js, src/components/transaction/DataCard/index.jsx
https://optimumpartners.atlassian.net/browse/REV-402
add message when table is empty
=> REV-402 transaction page add a message when no data found

src/components/create-listing/CreateListingForm/index.jsx, src/components/create-listing/ListingImageInput/index.jsx, src/components/my-profile/MyProfileWrapper/index.jsx, src/components/shared/FilesList/filesList.styles.js, src/components/shared/FilesList/index.jsx, src/components/transaction/UploadDocumentsWrapper/index.jsx, src/services/listing.js, src/services/upload.js
https://optimumpartners.atlassian.net/browse/REV-456
- add upload multiple listing images logic
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/78
=> REV-456-create-listing-edit-listing-upload-images

src/components/shared/Button/Button.style.js
Reverts abukhadraop-or/reverifi#281
=> Revert "REV-221 fix button on edit listings as on figma"

src/components/transaction/AddPartiesWrapper/add-parties-wrapper-schema.js, src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js, src/components/transaction/AddPartiesWrapper/index.jsx
=> REV-399-add final price

src/components/achievements/achievementsSidebar/index.jsx, src/components/home/ClaimAddress/claim-address.styles.js, src/components/home/ExploreListing/explore-listing.styles.js, src/components/home/ReverifiPlus/index.jsx, src/components/home/ReverifiPlus/reverifi-plus.styles.js, src/components/home/Storyboard/index.jsx, src/components/home/Storyboard/storyboard.styles.js, src/components/listing-search-page/ListingSearch/index.jsx, src/components/listing-search-page/ListingSearch/listing-search.style.js, src/components/listing-search-page/SearchHeader/index.jsx, src/components/shared/CustomMenuList/index.jsx, src/components/shared/Footer/footer.styles.js, src/components/shared/Footer/index.jsx, src/components/shared/Navbar/index.jsx, src/components/shared/Navbar/navbar.styles.js, src/components/shared/Sidebar/sidebar.styles.js, src/contexts/UserContext/index.jsx, src/styles/colors.js
Home page and menu responsive fixes
=> responsive changes

src/components/home/ClaimAddress/claim-address.styles.js, src/components/home/ExploreListing/explore-listing.styles.js, src/components/home/ReverifiPlus/reverifi-plus.styles.js
=> home page fixes

src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js, src/components/transaction/AddPartiesWrapper/index.jsx
https://optimumpartners.atlassian.net/browse/REV-517
=> REV-517 Add fix notes field width

src/components/my-listings/ListingsTable/listing-table.style.js, src/components/my-roles/RolesTable/index.jsx
https://optimumpartners.atlassian.net/browse/REV-357
=> remove comma

src/components/verify-phone/VerifyPhoneForm/index.jsx, src/components/verify-phone/VerifyPhoneForm/verify-phone-form.styles.js
https://optimumpartners.atlassian.net/browse/REV-140
=> fix verify you phone page

src/components/agent-details/AgentListings/index.jsx, src/components/home/FeaturedListingCard/index.jsx, src/components/listing-search-page/Card/index.jsx
https://optimumpartners.atlassian.net/browse/REV-510
=> REV-510-replace lot sqft with garages

src/components/listing-page/ContactForm/contact-form.styles.js
https://optimumpartners.atlassian.net/browse/REV-370
=> REV-370 fix form expanded when submit empty form

src/components/listing-page/Details/index.jsx
=> REV-383 fix leading zeros

src/components/create-listing/CreateListingForm/index.jsx, src/components/create-listing/ListingImageInput/index.jsx, src/components/create-listing/ListingImageInput/listingImageInput.styles.js, src/components/shared/FilesList/filesList.styles.js
https://optimumpartners.atlassian.net/browse/REV-456
- fix upload images
=> REV-456-fix-2

src/components/agent-details/CardInformation/index.jsx
=> REV-320 user can save listings from agent

src/components/transaction-info/TransactionInfoWrapper/index.jsx, src/components/transaction-info/TransactionsTable/index.jsx
https://optimumpartners.atlassian.net/browse/REV-511
- fix transaction bug
=> REV-511-fix

src/components/listing-page/ClaimPropertyModal/index.jsx, src/services/listing.js
https://optimumpartners.atlassian.net/browse/REV-11
- fix claim adderss services
- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/81
=> REV-11-FIX

src/components/my-listings/ListingsHeader/index.jsx
=> REV-522 remove filters from my listings page

src/components/listing-page/ContactForm/contact-form.styles.js, src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
=> REV-354-374 fixed fire fox issues

src/components/agent-list/AgentCard/agent-card.styles.js
=> REV-353 fix border on firefox browser

src/components/listing-search-page/SearchList/search-list.style.js
=> change font weight

src/pages/SignUp/SignUp.jsx, src/pages/SignUp/sign-up-schema.js
Confirm password
Add confirm password field to the signup page
=> add confirm password field to signup page

.github/workflows/cicd.yml
defined the following env var: REACT_APP_STAGING_URL=https://reverifi.sociumtech.com
=> Added new env var
